---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
    - name: Set executable user permissions on rc.local
      file:
        path: /etc/rc.d/rc.local
        owner: root
        group: root
        mode: 0744
    - name: Create /root/bin directory
      file:
        path: /root/bin
        state: directory
    - name: Set login banner
      copy:
        src: banner.txt
        dest: /etc/issue
        owner: root
        group: root
        mode: '0600'
    - name: Install additional packages
      yum:
        state: present
        name:
          - selinux-policy-devel
          - vim
          - rsyslog   
    - name: Start rsyslog
      systemd:
        name: rsyslog
        enabled: yes
        state: started 
    - name: Install prereq packages for Foreman
      yum:
        state: present
        name:
          - libnl3
          - python3-m2crypto 
          - python3-dmidecode 
          - python3-ethtool 
          - python3-inotify 
          - subscription-manager
          - python3-subscription-manager-rhsm
          - subscription-manager-rhsm-certificates 
          - usermode
