# Apply CIS CentOS Linux 8 Benchmark 1.0.0
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    # 1.1.2 Ensure separate partition exists for /tmp
    - name: unmask tmp.mount
      shell: systemctl unmask tmp.mount
    - name: enable tmp.mount
      shell: systemctl enable tmp.mount
    - name: Setup tmpfs on /tmp
      lineinfile:
        path: /etc/systemd/system/local-fs.target.wants/tmp.mount
        regexp: '^Options=mode=1777,strictatime$'
        line: 'Options=mode=1777,strictatime,nosuid,nodev,noexec,size=2G'
        backrefs: yes
    # 4.2.1.3 Ensure rsyslog default file permissions configured
    - name: Ensure rsyslog default file permissions configured
      lineinfile:
        path: /etc/rsyslog.conf
        line: $FileCreateMode 0640
    # 5.1.2 Ensure permissions on /etc/crontab are configured
    - name: Ensure permissions on /etc/crontab are configured
      file:
        path: /etc/crontab
        owner: root
        group: root
        mode: '0600'
    # 5.1.3 Ensure permissions on /etc/cron.hourly are configured
    - name: Ensure permissions on /etc/cron.hourly are configured
      file:
        path: /etc/cron.hourly
        owner: root
        group: root
        mode: '0700'
    # 5.1.4 Ensure permissions on /etc/cron.daily are configured
    - name: Ensure permissions on /etc/cron.daily are configured
      file:
        path: /etc/cron.daily
        owner: root
        group: root
        mode: '0700'
    # 5.1.5 Ensure permissions on /etc/cron.weekly are configured
    - name: Ensure permissions on /etc/cron.weekly are configured
      file:
        path: /etc/cron.weekly
        owner: root
        group: root
        mode: '0700'
    # 5.1.6 Ensure permissions on /etc/cron.monthly are configured
    - name: Ensure permissions on /etc/cron.monthly are configured
      file:
        path: /etc/cron.monthly
        owner: root
        group: root
        mode: '0700'    
    # 5.1.7 Ensure permissions on /etc/cron.d are configured
    - name: Ensure permissions on /etc/cron.d are configured
      file:
        path: /etc/cron.d
        owner: root
        group: root
        mode: '0700'
    # 5.1.8 Ensure at/cron is restricted to authorized users
    - name: Ensure /etc/cron.deny doesn't exist
      file:
        path: /etc/cron.deny
        state: absent
    - name: Ensure /etc/at.deny doesn't exist
      file:
        path: /etc/at.deny
        state: absent
    - name: Create /etc/cron.allow
      file:
        path: /etc/cron.allow
        state: touch
        owner: root
        group: root
        mode: '0600'
    - name: Create /etc/at.allow
      file:
        path: /etc/at.allow
        state: touch
        owner: root
        group: root
        mode: '0600'

    # 5.4.1 Ensure password creation requirements are configured 
    - name: Copy over pwquality config file
      copy:
        src: pwquality.conf
        dest: /etc/security/pwquality.conf
        owner: root
        group: root
        mode: '0644'
    # 5.4.2 Ensure lockout for failed password attempts is configured
    - name: Copy over password-auth file
      copy:
        src: password-auth-ac
        dest: /etc/pam.d/password-auth-ac
        owner: root
        group: root
        mode: '0644'
    - name: Copy over system-auth file
      copy:
        src: system-auth-ac
        dest: /etc/pam.d/system-auth-ac
        owner: root
        group: root
        mode: '0644'
    # 5.4.3 Ensure password reuse is limited
    - name: Uncomment pam_wheel.so use_uid
      lineinfile: 
        path: /etc/pam.d/su
        regexp: '^#auth\s.*required\s.*pam_wheel.so use_uid'
        line: 'auth            required        pam_wheel.so use_uid'
        backrefs: yes

        
    # 5.4.1.2 Ensure minimum days between password changes is 7 or more
    - name: Ensure minimum days between password changes is 7
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MIN_DAYS'
        line: 'PASS_MIN_DAYS 7'
        backrefs: yes
    # 5.4.4 Ensure default user umask is 027 or more restrictive
    - name: Set umask 027 for user files in profile
      lineinfile:
        path: /etc/profile
        regexp: '    umask'
        line: '    umask 027'
        backrefs: yes
    - name: Set umask 027 for user files in bashrc
      lineinfile:
        path: /etc/bashrc
        regexp: '       umask'
        line: '       umask 027'
        backrefs: yes
    # 5.4.5 Ensure default user shell timeout is 900 seconds or less
    - name: Ensure default user shell timeout is 600 seconds in /etc/bashrc
      lineinfile:
        path: /etc/bashrc
        line: TMOUT=600
    - name: Ensure default user shell timeout is 600 seconds in /etc/profile
      lineinfile:
        path: /etc/profile
        line: TMOUT=600
    # 6.2.8 Ensure users' home directories permissions are 750 or more restrictive
    # During an audit, it was found that /home/cwagent did not exist
    - name: Register for Ansible check if user cwagent found
      shell: "cat /etc/passwd | grep cwagent | awk -F : '{print $1}'"
      register: user_cwagent
    - name: Create cwagent home dir
      when: '"cwagent" in user_cwagent.stdout_lines'
      file:
        path: /home/cwagent
        state: directory
        owner: cwagent
        group: cwagent
        mode: '0700'
        