# Apply CIS CentOS Linux 8 Benchmark 1.0.0
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    # 5.4.1 Ensure password creation requirements are configured 
    - name: Copy over pwquality config file
      copy:
        src: pwquality.conf
        dest: /etc/security/pwquality.conf
        owner: root
        group: root
        mode: '0644'
    # 5.4.2 Ensure lockout for failed password attempts is configured
    - name: Copy over password-auth file
      copy:
        src: password-auth-ac
        dest: /etc/pam.d/password-auth-ac
        owner: root
        group: root
        mode: '0644'
    - name: Copy over system-auth file
      copy:
        src: system-auth-ac
        dest: /etc/pam.d/system-auth-ac
        owner: root
        group: root
        mode: '0644'
    # 5.4.3 Ensure password reuse is limited
    - name: Uncomment pam_wheel.so use_uid
      lineinfile: 
        path: /etc/pam.d/su
        regexp: '^#auth\s.*required\s.*pam_wheel.so use_uid'
        line: 'auth            required        pam_wheel.so use_uid'
        backrefs: yes
