---
- hosts: 127.0.0.1
  connection: local
  vars:
    #mydisk: /dev/nvme0n1
    mydisk: /dev/sda
    #mypart2: /dev/nvme0n1p2
    mypart2: /dev/sda2
    #mypart3: /dev/nvme0n1p3
    mypart3: /dev/sda3
  tasks:
    - name: Find size of partition 2
      shell: parted -s {{ mydisk }} print | grep "^ 2" | awk {'print $3'}
      register: part2size
    - name: Create second partition for VG CIS mounts
      parted:
        device: "{{ mydisk }}"
        number: 3
        part_start: "{{ part2size.stdout }}"
        flags: [ lvm ]
        state: present
    - name: Run partprobe
      command: partprobe
    - name: Install lvm package
      yum: 
        name: lvm2
        state: latest
    - name: Create volume group "vg"
      lvg:
        vg: vg
        pvs: "{{ mypart3 }}"
    - name: Create logical volume "tmp"
      lvol:
        vg: vg
        lv: lv_tmp
        size: 2g
    - name: Create logical volume "var"
      lvol:
        vg: vg
        lv: lv_var
        size: 22g
    - name: Create logical volume "var_log"
      lvol:
        vg: vg
        lv: lv_var_log
        size: 12g
    - name: Create logical volume "var_log_audit"
      lvol:
        vg: vg
        lv: lv_var_log_audit
        size: 14g
    - name: Create logical volume "home" with remaining space
      lvol:
        vg: vg
        lv: lv_home
        size: 100%FREE
        shrink: false
    - name: Create XFS file system for vg-lv_tmp
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_tmp
    - name: Create XFS file system for vg-lv_var
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_var
    - name: Create XFS file system for vg-lv_var_log
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_var_log
    - name: Create XFS file system for vg-lv_var_log_audit
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_var_log_audit
    - name: Create XFS file system for vg-lv_home
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_home
