---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "Copy service files"
      copy:
        src: "{{ item }}"
        dest: /etc/firewalld/services/
        owner: root
        group: root
        mode: 0644
      with_items:
        - ncpa.xml
        - nessus.xml
        - ssh.xml
    - name: "Copy zone file"
      copy:
        src: "{{ item }}"
        dest: /etc/firewalld/zones/
        owner: root
        group: root
        mode: 0644
      with_items:
        - hipaa.xml
    - name: "Enable and restart firewalld"
      systemd:
        name: firewalld
        enabled: yes
        state: restarted
    - name: "Set default zone"
      shell: "firewall-cmd --set-default-zone hipaa"
