---
- hosts: all
  user: foreman
  become: true
  vars:
  tasks:
    - name: "Find setuid-setgid files"
      shell: find / -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null
      register: found_setuid_setgid
    - name: "Create rules file"
      file:
        path: /etc/audit/rules.d/setuid-setgid.rules
        state: touch
    - name: "Add lines to rules file"
      lineinfile:
        path: /etc/audit/rules.d/setuid-setgid.rules
        line: '-a always,exit -F path={{ item }} -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged'
      with_items: "{{ found_setuid_setgid.stdout_lines }}"
    - name: "Disable core dumps for users"
      lineinfile:
        path: /etc/security/limits.conf
        line: "*\thard\tcore\t0"
    - name: "Fetch fix-rpm-perms script and run it"
      shell: /root/bin/fetch -ef fix-rpm-perms
    - name: "Set log permissions"
      file:
        path: /var/log/{{ item }}
        mode: '0600'
      with_items:
        - cron
        - spooler
        - boot.log
        - maillog
        - messages
        - secure

