---
- hosts: 127.0.0.1
  connection: local
  tasks:
    # 3.6 Disable IPv6
    # 4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled
    # 4.1.1.4 Ensure audit_backlog_limit is sufficient
    - name: Copy grub script
      copy:
        src: fix-grub-default
        dest: /root/bin/fix-grub-default
        owner: root
        group: root
        mode: '0700'
    - name: Run grub script
      shell: "/root/bin/fix-grub-default"
    # 1.5.1 Ensure permissions on bootloader config are configured 
    - name: Set root ownership on grub.cfg
      shell: "chown root:root /boot/grub2/grub.cfg"
    - name: Set file mode permissinons on grub.cfg
      shell: "chmod og-rwx /boot/grub2/grub.cfg"
    - name: Set root ownership on grubenv
      shell: "chown root:root /boot/grub2/grubenv"
    - name: Set file mode permissinons on grubenv
      shell: "chmod og-rwx /boot/grub2/grubenv"
    # 4.1.3 Ensure changes to system administration scope (sudoers) is collected
    # 4.1.4 Ensure login and logout events are collected
    # 4.1.5 Ensure session initiation information is collected
    # 4.1.6 Ensure events that modify date and time information are collected
    # 4.1.7 Ensure events that modify the system's Mandatory Access Controls are collected 
    # 4.1.8 Ensure events that modify the system's network environment are collected
    # 4.1.9 Ensure discretionary access control permission modification events are collected
    # 4.1.10 Ensure unsuccessful unauthorized file access attempts are collected
    # 4.1.11 Ensure events that modify user/group information are collected
    # 4.1.12 Ensure successful file system mounts are collected
    # Note: "4.1.13 Ensure use of privileged commands is collected" is done in grub-ipv6-enable-audit.yaml
    # 4.1.14 Ensure file deletion events by users are collected 
    # 4.1.15 Ensure kernel module loading and unloading is collected 
    # 4.1.16 Ensure system administrator actions (sudolog) are collected
    # 4.1.17 Ensure the audit configuration is immutable
    - name: Copy over audit rules file
      copy:
        src: sdsc-hipaa.rules
        dest: /etc/audit/rules.d/sdsc-hipaa.rules
        owner: root
        group: root
        mode: '0644'
