# To explicitly prevent cloud-initramfs-tools from running growroot, 
# the file /etc/growroot-disabled can be created.
# https://cloudinit.readthedocs.io/en/latest/topics/modules.html#growpart
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create cloud-init file that disables root growpart
      file: 
        path: /etc/growroot-disabled
        state: touch
        owner: root
        group: root
        mode: 0644
    - name: Create growpart.cfg to disable auto partition resize
      copy: 
        dest: "/etc/cloud/cloud.cfg.d/99_growpart.cfg"
        owner: root
        group: root
        mode: 0644
        content: |
          growpart:
            mode: off
            devices: ["/"]
            ignore_growroot_disabled: false
