---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create swap file
      command: dd if=/dev/zero of=/swapfile bs=1M count=4096 creates=/swapfile
    - name: Set permissions on swap file
      file: 
        path: /swapfile
        owner: root
        group: root
        mode: '0600'
    - name: Check swap file type
      command: file /swapfile
      register: swapfile
    - name: Make swap file
      command: mkswap /swapfile
      when: swapfile.stdout.find('swap file') == -1
    - name: Write swap entry to fstab
      mount:
        path: swap
        src: /swapfile
        fstype: swap
        opts: defaults
        passno: 0
        dump: 0
        state: present
    - name: Mount swap
      command: swapon /swapfile
      when: ansible_swaptotal_mb < 1
