---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Find size of partition 1
      shell: parted /dev/vda1 print | grep "^Disk /dev/vda1" | awk {'print $3'}
      register: part1size
    - name: Create second partition for VG CIS mounts
      parted:
        device: /dev/vda
        number: 2
        part_start: "{{ part1size.stdout }}"
        flags: [ lvm ]
        state: present
    - name: Install lvm package
      yum: 
        name: lvm2
        state: latest
    - name: Create volume group "vg"
      lvg:
        vg: vg
        pvs: /dev/vda2
    - name: Create logical volume "tmp"
      lvol:
        vg: vg
        lv: lv_tmp
        size: 2g
    - name: Create logical volume "var"
      lvol:
        vg: vg
        lv: lv_var
        size: 22g
    - name: Create logical volume "var_log"
      lvol:
        vg: vg
        lv: lv_var_log
        size: 12g
    - name: Create logical volume "var_log_audit"
      lvol:
        vg: vg
        lv: lv_var_log_audit
        size: 14g
    - name: Create logical volume "home" with remaining space
      lvol:
        vg: vg
        lv: lv_home
        size: 100%FREE
        shrink: false
    - name: Create XFS file system for vg-lv_tmp
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_tmp
    - name: Create XFS file system for vg-lv_var
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_var
    - name: Create XFS file system for vg-lv_var_log
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_var_log
    - name: Create XFS file system for vg-lv_var_log_audit
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_var_log_audit
    - name: Create XFS file system for vg-lv_home
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv_home
